function getEps(x, y, epsFile, width, height, fontSize, xLabel, yLabel, Title, Axis, xTicks, yTicks)
    figure('Units','inches',...
        'Position',[0 0 width height],...
        'PaperPositionMode','auto');
    
    plot(x, y);
    
    axis(Axis);
    
    set(gca,...
        'Units','normalized',...
        'YTick',yTicks,...
        'XTick',xTicks,...
        'Position',[.15 .2 .75 .7],...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',fontSize,...
        'FontName','Times')
    
    xlabel(xLabel,...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',fontSize,...
        'FontName','Times');
    
    ylabel(yLabel,...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',fontSize,...
        'FontName','Times');
    
    title(Title,...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontWeight','normal',...
        'FontSize',fontSize,...
        'FontName','Times')
    
    print( gcf, '-depsc2', epsFile )
end