%%
epsFile = 'residual-moment-infinity-loops.eps';
xLabel = '$\theta_2$ (in deg)';
yLabel = 'Residual Moment (in N-mm)';
Title = 'Residual moment for various applied forces';
Legend = {'F = 10N in horizontal direction','F = 10N in vertical direction'};

Axis = [-180 180 -5000 5000];
xTicks = -180:30:180;
yTicks = -5000:1000:5000;

width = 150;
height = 100;
fontSize = 22;

x = th*180/pi;
y = torque;

%%
figure('Units','centimeters',...
    'Position',[0 0 width height],...
    'PaperPositionMode','auto');

plot(x, y,...
    'LineWidth',1.0);

hold on;
plot([Axis(1), Axis(2)], [0, 0],...
    'LineWidth',1.5,...
    'Color','k');

axis(Axis);

set(gca,...
    'Units','normalized',...
    'YTick',yTicks,...
    'XTick',xTicks,...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times',...
    'XColor','k',...
    'YColor','k',...
    'ZColor','k')

xlabel(xLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

ylabel(yLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

title(Title,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times')

legend(Legend,...
    'Location', 'NorthEast')
    
%%
print( gcf, '-depsc2', epsFile );
close(gcf);