%%
epsFile = 'residual-moment-var-ang-10.eps';
xLabel = '$\theta_2$ (in deg)';
yLabel = 'Residual Moment (in N-mm)';
Title = 'Residual moment for constant force of 10N applied from different direction';
Axis = [-50 25 -70 70];
xTicks = -50:5:25;
yTicks = -70:10:70;

width = 150;
height = 100;
fontSize = 22;

x = th*180/pi;
y = permute(torque(:,51,:),[1,3,2]);

%%
figure('Units','centimeters',...
    'Position',[0 0 width height],...
    'PaperPositionMode','auto');

plot(x, y,...
    'LineWidth',1.0);

hold on;
plot([Axis(1), Axis(2)], [0, 0],...
    'LineWidth',1.5,...
    'Color','k');

axis(Axis);

set(gca,...
    'Units','normalized',...
    'YTick',yTicks,...
    'XTick',xTicks,...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times',...
    'XColor','k',...
    'YColor','k',...
    'ZColor','k')

xlabel(xLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

ylabel(yLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

title(Title,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times')

%%
print( gcf, '-depsc2', epsFile );
close(gcf);