%%
epsFile = 'residual-moment-var-mag-102.eps';
xLabel = '$\theta_2$ (in deg)';
yLabel = 'Residual Moment (in N-mm)';
Title = 'Residual moment for varying magnitude of applied forces at an angle of $102^{\circ}$';
Axis = [-5 -1 -10 10];
xTicks = -5:0.5:-1;
yTicks = -10:2:10;

width = 150;
height = 100;
fontSize = 22;

x = crankAngle * 180 / pi;
y = residualMoment(:,:,18);

%%
figure('Units','centimeters',...
    'Position',[0 0 width height],...
    'PaperPositionMode','auto');

plot(x, y,...
    'LineWidth',1.0);

hold on;
plot([Axis(1), Axis(2)], [0, 0],...
    'LineWidth',1.5,...
    'Color','k');

axis(Axis);

set(gca,...
    'Units','normalized',...
    'YTick',yTicks,...
    'XTick',xTicks,...
    'Position',[.15 .2 .75 .7],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times',...
    'XColor','k',...
    'YColor','k',...
    'ZColor','k')

xlabel(xLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

ylabel(yLabel,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',fontSize,...
    'FontName','Times');

title(Title,...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',fontSize,...
    'FontName','Times')

annotation('arrow',[0.43,0.48],[0.58,0.75],...
    'LineStyle','--',...
    'LineWidth',1.0,...
    'HeadStyle','cback2');

annotation('textbox',[0.48, 0.7, 0.5, 0.5 ],...
    'String','Increasing Magnitude of Applied Force',...
    'Interpreter', 'latex',...
    'FontSize', fontSize,...
    'VerticalAlignment','bottom',...
    'LineStyle','None',...
    'FitBoxToText','on');

%%
print( gcf, '-depsc2', epsFile );
close(gcf);